### ISSUE TITLE
Command line script

### ISSUE THREAD

**Issue by tlocke** [schlitzered/pep3143daemon#4]
Hi, I've been looking for a replacement for [Python-Daemon](https://alioth.debian.org/projects/python-daemon/) because of Python 3 compatibility problems, and pep3143daemon looks good. There's one thing that's in Python-Daemon that's not in pep3143daemon that I'd miss, and that's the daemon runner class for easily making a command line script that gives you start | stop | restart functionality. If I were to submit a pull request to do this, would you consider including it? Thanks, Tony.

**Comment by schlitzered** [comment]
Hey Tony,

i just had a look at what the python-daemon "DaemonRunner" class is doing. Basically it takes some object with a "run" method, and wraps it in another class with start/stop/restart capabilities.

Did you had in mind to implement something like this? because I do not feel like this should be added, it looks a little to restricted to one use case in my point of view.  I myself is using the pep3143daemon class most of the time like this:

[sample_daemon](https://github.com/schlitzered/el_aap/blob/master/el_aap/__init__.py)

but I also do not feel like adding this to the lib, because i think there is no general approach that will fit all use cases.

Regards,

Stephan

**Comment by tlocke** [comment]
Thanks @schlitzered, that example is just what I need. I'll give it a try.

**Comment by schlitzered** [comment]
Cool, let me know if you have any question, otherwise I will close this issue in a several days.
