### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by heri16** [schlitzered/pep3143daemon#6]
Is this project abandoned?

**Comment by schlitzered** [comment]
no, i would just call it feature complete at the moment. do you have any issues using the lib?

FYI: this lib exists because at the time it was created, python-daemon was not able to run on python3, i am not sure if python-daemon nowadays support python 3. never checked it. besides this, it is implementing the same pep. this lib and python-daemon offer a different pidfile implementation.

check for yourself, which of them suites your needs better.

**Comment by heri16** [comment]
How does this compare to python-daemon? Are they the same?
